export const ADD_NUMBER_ACTIONS = "ADD_NUMBER_ACTIONS";
export const SUB_NUMBER_ACTIONS = "SUB_NUMBER_ACTIONS";
export const CHANGE_BANNERS = "CHANGE_BANNERS";
export const CHANGE_RECOMMENDS = "CHANGE_RECOMMENDS";
